---
title: "Formative Assessment 3"
author: "Vera Aguila"
date: "2024-09-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Find Q1, Q2, Q3, D9, and P95 and other measures for the following sample of test scores: (See expected table of descriptive measures below.)

88 45 53 86 33 86 85 30 89 53 41 96 56 38 62
71 51 86 68 29 28 47 33 37 25 36 33 94 73 46
42 34 79 72 88 99 82 62 57 42 28 55 67 62 60
96 61 57 75 93 34 75 53 32 28 73 51 69 91 35

<br><br>
Descriptive Statistics
```{r che}

library(e1071)  
library(knitr)  
library(kableExtra)  
score<-c(88,45,53,86,33,86,85,30,89,53,41,96,56,38,62,71,51,86,68,29,28,47,33,37,25,36,33,94,73,46,42,34,79,72,88,99,82,62,57,42,28,55,67,62,60,96,61,57,75,93,34,75,53,32,28,73,51,69,91,35)


mean_score <- mean(score)
median_score <- median(score)
mode_score <- as.numeric(names(sort(-table(score)))[1]) 
std_dev <- sd(score)
variance <- var(score)
skewness_val <- skewness(score)
kurtosis_val <- kurtosis(score) - 3 
min_score <- min(score)
max_score <- max(score)
percentiles <- quantile(score, probs = c(0.25, 0.50, 0.75, 0.90, 0.95))


stats_table <- data.frame(
  Statistic = c("Valid", "Mode", "Median", "Mean", "Std. Deviation", "Variance", 
                "Skewness", "Std. Error of Skewness", "Kurtosis", "Std. Error of Kurtosis", 
                "Minimum", "Maximum", "25th percentile", "50th percentile", 
                "75th percentile", "90th percentile", "95th percentile"),
  Score = c(length(score), mode_score, median_score, mean_score, std_dev, variance, 
            skewness_val, 0.309, kurtosis_val, 0.608, 
            min_score, max_score, 
            percentiles[1], percentiles[2], percentiles[3], percentiles[4], percentiles[5])
)

kable(stats_table, col.names = c(" ", "Score"), align = c("l","r"), digits = 3, format = "html", caption ="Descriptive Statistics" )%>%
  kable_styling(full_width = F, position = "center",bootstrap_options = c("condensed")) %>%
  row_spec(0, align= "center", extra_css = "border-top: 2px solid black")%>%
  row_spec(1, extra_css = "border-top: 2px solid black") %>%  
  row_spec(17, extra_css = "border-bottom: 2px solid black") %>%  
  row_spec(2, background = "#f0f0f0") %>%  
  row_spec(4, background = "#f0f0f0") %>% 
  row_spec(6, background = "#f0f0f0") %>%  
  row_spec(8, background = "#f0f0f0") %>%  
  row_spec(10, background = "#f0f0f0") %>%  
  row_spec(12, background = "#f0f0f0") %>%  
  row_spec(14, background = "#f0f0f0") %>%  
  row_spec(16, background = "#f0f0f0") %>%  
  footnote(alphabet = "More than one mode exists, only the first is reported")


```





